controller_list:
  - name: yumi/joint_vel_controller_l
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - yumi_joint_1_l
      - yumi_joint_2_l
      - yumi_joint_7_l
      - yumi_joint_3_l
      - yumi_joint_4_l
      - yumi_joint_5_l
      - yumi_joint_6_l

  - name: yumi/joint_vel_controller_r
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - yumi_joint_1_r
      - yumi_joint_2_r
      - yumi_joint_7_r
      - yumi_joint_3_r
      - yumi_joint_4_r
      - yumi_joint_5_r
      - yumi_joint_6_r